name: Build and publish wheels

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Build wheels
    #   uses: messense/maturin-action@v1
    #   with:
    #     maturin-version: latest
    #     manylinux: auto
    #     command: build
    #     args: --release
    - name: Publish wheels
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        manylinux: auto
        command: publish
        args: --no-sdist -u __token__
      env:
        MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}

#       args: --no-sdist -u __token__ -r https://test.pypi.org/legacy/
#       MATURIN_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
